import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Copy, Download, Shield, Share2, Check } from 'lucide-react'
import { useTheme } from '../context/ThemeContext'

export default function ShareScoreModal({ isOpen, onClose, score, category }) {
  const [copied, setCopied] = useState(false)
  const { theme } = useTheme()

  const handleCopyLink = () => {
    const url = `${window.location.origin}/dashboard?demo=true`
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  if (!isOpen) return null

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[200] flex items-center justify-center px-4"
        >
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />

          {/* Modal */}
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
            transition={{ type: 'spring', damping: 25 }}
            className={`relative w-full max-w-md rounded-3xl border p-6 shadow-2xl ${
              theme === 'dark' ? 'bg-[#111] border-[#1f1f1f]' : 'bg-white border-gray-200'
            }`}
          >
            {/* Close button */}
            <button
              onClick={onClose}
              className={`absolute top-4 right-4 p-2 rounded-xl transition ${
                theme === 'dark' ? 'hover:bg-[#1a1a1a] text-gray-400' : 'hover:bg-gray-100 text-gray-500'
              }`}
            >
              <X size={18} />
            </button>

            <h3 className={`text-lg font-bold mb-4 ${theme === 'dark' ? 'text-white' : 'text-gray-900'}`}>
              Share Your Score
            </h3>

            {/* Score Card Preview */}
            <div className="relative rounded-2xl overflow-hidden mb-6">
              <div className="bg-gradient-to-br from-[#0a0a0a] to-[#1a1a2e] p-8 text-center">
                {/* Decorative elements */}
                <div className="absolute top-4 left-4 w-20 h-20 bg-blue-500/10 rounded-full blur-2xl" />
                <div className="absolute bottom-4 right-4 w-16 h-16 bg-teal-500/10 rounded-full blur-2xl" />

                {/* Logo */}
                <div className="flex items-center justify-center gap-2 mb-6">
                  <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-blue-500 to-teal-500 flex items-center justify-center">
                    <Shield size={14} className="text-white" />
                  </div>
                  <span className="text-sm font-bold bg-gradient-to-r from-blue-400 to-teal-400 bg-clip-text text-transparent">
                    ScoreKu
                  </span>
                </div>

                {/* Score */}
                <div className="relative inline-flex items-center justify-center w-28 h-28 mb-4">
                  <svg className="w-28 h-28 -rotate-90" viewBox="0 0 120 120">
                    <circle cx="60" cy="60" r="50" fill="none" stroke="#1f1f1f" strokeWidth="6" />
                    <circle
                      cx="60" cy="60" r="50" fill="none"
                      stroke="url(#shareGradient)"
                      strokeWidth="6"
                      strokeLinecap="round"
                      strokeDasharray={`${(score / 100) * 314} 314`}
                    />
                    <defs>
                      <linearGradient id="shareGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                        <stop offset="0%" stopColor="#2563eb" />
                        <stop offset="100%" stopColor="#14b8a6" />
                      </linearGradient>
                    </defs>
                  </svg>
                  <span className="absolute text-3xl font-bold text-white">{score}</span>
                </div>

                {/* Category */}
                <div
                  className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold mb-4"
                  style={{
                    color: category.color,
                    backgroundColor: `${category.color}15`,
                    border: `1px solid ${category.color}30`,
                  }}
                >
                  <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: category.color }} />
                  {category.label}
                </div>

                {/* Footer */}
                <p className="text-[11px] text-gray-500 mt-2">
                  Generated by ScoreKu - AI Alternative Credit Scoring
                </p>
                <p className="text-[10px] text-gray-600 mt-1">scoreku.vercel.app</p>
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3">
              <button
                onClick={handleCopyLink}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-medium transition-all ${
                  theme === 'dark'
                    ? 'bg-[#1a1a1a] border border-[#2a2a2a] text-white hover:border-blue-500/30'
                    : 'bg-gray-100 border border-gray-200 text-gray-800 hover:border-blue-300'
                }`}
              >
                {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
                {copied ? 'Copied!' : 'Copy Link'}
              </button>
              <button
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl text-sm font-medium transition-all ${
                  theme === 'dark'
                    ? 'bg-[#1a1a1a] border border-[#2a2a2a] text-white hover:border-teal-500/30'
                    : 'bg-gray-100 border border-gray-200 text-gray-800 hover:border-teal-300'
                }`}
                title="Screenshot this card!"
              >
                <Download size={14} />
                Screenshot this!
              </button>
            </div>

            <p className={`text-center text-[11px] mt-3 ${theme === 'dark' ? 'text-gray-600' : 'text-gray-400'}`}>
              Tip: Screenshot the card above to share on social media!
            </p>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
